language: clojure
sudo: required
services:
  - docker
before_install:
  - docker pull clojusc/mesos:1.0.1
  - docker run -d -p 5050:5050 clojusc/mesos:1.0.1
script:
  - lein build-check
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - LEIN_SNAPSHOTS_IN_RELEASE=true
notifications:
  email:
      - oubiwann@gmail.com

